language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: al7/mMnCmdworX2CbLwD8kSw9o6wGrNQwjFmlK00bNpKTFczzIZQJN5lzeR7airEXCq4oCCZno8eRNrhwieYKDMzw8Wq2la5J/LZSCCuzNiu8D5PYjqpUeEGyODLwdtxQs9F0JkwIZDaranKst5gKVzuFKGnYNI7XYzr8tTZvmInKS+g/oZ4nNlCIjm11jc0a+ejB9OKmDuybysLZFnlQdFaiq30fNVokimK2nSCGj8WdFXsWGk8dhwfQJsNlL7YDG9WBl6V46mhEoBqsWy3hVxBzrklpujBTgznJRQLWCeJSycbZvSZsv1rnrsL9xXZ4o+qPurAko2XRsYaoNY5Y6+5lzfoyTFJepvvXkCH3diyQfroShhpyw2riWXVTbnKL6iNkqH75w0JchBJ26oGxtmkki56OV+k2gCnIjIf4RhwYgzKW87SWerYa5vuaRMj7NI/Xphrd/ByHRbvTqK7NBxypKFkUK+rNhHYXIz3F5/5jh1lQ3kRxDCPFkaogk6VeJHRccS0dKBMlrxkiaUMwDucKmjCWRAsODk5LnmVCBXWd4Tlyxq6OCfmEI3R7alaO+RuKfG3EeG/LcdMqth/IltlHGoMAQiTGc9O4GETq/Ydel+vLYIRqFmFBFXShsd5cXpNPuTdVPVxsYSl0YLDd5UchoOXW5h+B86L+7z/V34=
  - secure: vc/ZMMQqb02iQHr8u1DDQm9+8BqYJYKMCcOheZ3jE2uyp2WIZ7DamlGkQs9mXgPzoAkxSKc9MaDesyelAhf5EwUR+lJUvG2Sp8vq9UAQYC3Mgu07OthvrD9jE1tDl8JBXMUnOERlZd/VD9dmPetOl1947KcDHPUB7rikNGSgrzp7fxKDxdJeESkAlc2KZTNvD/Jv0IFvsHopUhO5frM0vVkn6L264lY8BJO21nRNPDMRl8XoW1qN8WYRG38eWUxJgkOSQ4FaPzTU4ApjqaHDhXorLo29d6d2gsJhuFwrRTiCbiXFnXoMQsPMfxR7l1wfLGO+yJqvJtcs+dBI4mWRUDt53iejukuY3YWRcRaE92JOSseW8CcFu/ie2q3hyDKmEn2xqoO0+3SbEgeqTcgWIUnV75aMsQuj+9/vNpIuIEp1ZiQX34ssDpqg9Pw8j/zQuXgTbzo0hh98f4jOBVGUSzJ0l2N0NqcitQoDX1cle2X7ObWPcH/r+TTgO2DjHgYJHgzbcrDMqvvsmQ00kWTpuiP0WCqcIod66vtI/u8SS9viDrdQgJIFhOXeQSOFgaFZqrkGPx1cr+XVUHDv5Y9LIloclBQ6d9bss0rNNizC20DW+EUwR25ttOPZcQo7cgQ5F+Tr9+ho1fPGEpQEKii5ZXqYQRWZy57Wzd4N6dFJLlY=
